### ISSUE TITLE
pip install

### ISSUE THREAD

**Issue by Kitryn** [evonove/mkm-sdk#1]
Running `pip install mkmsdk` fails, giving error:
```
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 20, in <module>
      File "/private/var/folders/2r/1fpbx4gn3z76yy01z6crpd3h0000gn/T/pip-build-yHXp3_/mkmsdk/setup.py", line 21, in <module>
        history = open('HISTORY.rst').read().replace('.. :changelog:', '')
    IOError: [Errno 2] No such file or directory: 'HISTORY.rst'
```

Downloading the tar.gz from PyPI, extracting and adding the HISTORY.rst file from this repository, then running `pip install <local dir>` successfully installed the package

**Comment by Alien1993** [comment]
Thank you! I've verified the problem, the HISTORY.rst file is missing from the pip package so this is causing this issue. I'll fix it as soon as possible.

**Comment by Alien1993** [comment]
Fixed! It should work correctly right now.
