### ISSUE TITLE
Wants List Items not implemented?

### ISSUE THREAD

**Issue by koenbud** [evonove/mkm-sdk#31]
First of all thanks for the effort you have put into this awesome Python module.

I've looked closely at api_map.py and am unable to figure out how to use the wantslist items api endpoint. This endpoint returns the items in a specified wants list. I am able to get a list of want lists, but not the cards on the lists.

This is the documentation for the endpoint I am referring to: https://www.mkmapi.eu/ws/documentation/API_2.0:Wantslist_Item

**Comment by Alien1993** [comment]
Hi @koenbud, that endpoint has been added recently in API 2.0 of Magic Kard Market. As you can see from [their documentations](https://www.mkmapi.eu/ws/documentation/API_2.0:Main_Page) 2.0 works only on their sandbox servers.

> With the introduction of the 2.0 version all versions of the API will run parallel on our servers (2.0 beta currently only on the sandbox server).
Once 2.0 hits the live servers, we'll discontinue support for 1.0, while support for 1.1 will last until the next major API version. Nevertheless you can still access all 1.0 requests as normal.

As of now MKM-SDK supports only API 1.1, the endpoint you're referring to doesn't exist in this version.

In the coming weeks I should be able to start work on supporting API 2.0 at least on their sandbox.

**Comment by koenbud** [comment]
Thanks for the quick reply. I was not aware of that.

**Comment by Alien1993** [comment]
Just want to leave a quick update about API 2.0 and why work hasn't started on MKM-SDK.
 
Magic Kard Market's official sandbox is down or having issues by a month or so, until they fix it I can't test anything or see what's new in API 2.0. As of now I can only wait for them to release a fix before starting to work on it.

**Comment by koenbud** [comment]
Alright, thanks for the update!

**Comment by Alien1993** [comment]
Fixed in #40
