### ISSUE TITLE
Client does not handle redirects correctly

### ISSUE THREAD

**Issue by Xaerxess** [evonove/mkm-sdk#32]
If an endpoint returns 307 redirect, Python requests library is configured to follow it automatically. Unfortunately, it doesn't work because of how OAuth works.

From [MKM API 1.1 docs](https://www.mkmapi.eu/ws/documentation/API_1.1:Main_Page#307_Temporary_Redirect):

> 307 Temporary Redirect
> There are some requests that can return this HTTP status code:
> 
> - /orders/:actor/:state[/:start]
> - /stock[/:start]
> 
> In cases you requests one of these requests unpaginated and the response would return more than 100 entities, the response is a 307 telling you to instead call a paginated request with the start parameter. This has mainly performance reasons because these requests produce a lot of work for the server and can take a long time when called unpaginated.
> 
> Attention: Some implementations try to perform a 307 Temporary Redirect instantly and without further notice. This will leed to a 401 Unauthorized, because the OAuth signature for the original request is not valid for the request delivered with the 307 Temporary Redirect.

I encountered this when requesting `mkm.order_management.orders`, which in my case returned 307 redirect to paginated endpoint. Using `mkm.order_management.orders_paginated` with `start=1` is ok though.

**Comment by Alien1993** [comment]
Hi @Xaerxess, thank you for submitting this issue and sorry for the late response, I missed the notification. 

Sadly as of now I can't work on the project since MKM sandbox is down by a long time and I can't test any fix or new feature. 
As soon as the their sandbox comes back up I'll be able to fix.

**Comment by Alien1993** [comment]
Fixed in #38
