### ISSUE TITLE
find_messages not working

### ISSUE THREAD

**Issue by nique21** [evonove/mkm-sdk#44]
I'm trying to filter messages with your SDK but to no avail. What I'm trying to do:
```
mkm = Mkm(_API_MAP["2.0"]["api"], _API_MAP["2.0"]["api_root"])
response = mkm.account_management.find_messages(params={"unread": "false"})
```
But I always get a BAD REQUEST (400) error.

Ideally, I would like get this to work:
```
dt = datetime.datetime(2017, 1, 1)
response = mkm.account_management.find_messages(startDate=dt)
```
or even this:
`response = mkm.account_management.find_messages(params={"startDate": "2017-01-01"})`
But nothing seems to work. For reference, this is the API call I'm trying to do:

[API-Find-messages](https://api.cardmarket.com/ws/documentation/API_2.0:Account_Find_Messages)

Thanks

**Comment by silvanocerza** [comment]
From my understanding of the documentation if the `unread` parameter is used by itself it can only be set to `true`, so a 400 in that case it correct, probably they do so to avoid a too big response. 

This one can't work, all parameters must be strings, there's no automatic conversion.
```
dt = datetime.datetime(2017, 1, 1)
response = mkm.account_management.find_messages(startDate=dt)
```

I've tried this exact request and it returned 2xx correctly for me, I can't reproduce the error.
```
response = mkm.account_management.find_messages(params={"startDate": "2017-01-01"})
```
What kind of error are you getting? Are you making a dedicated or a widget app? Widgets apps don't have access to any of the Account Management endpoints so that might be it.

**Comment by nique21** [comment]
Thanks for the fast reply. I have set up all the MKM_* environment variables and, in fact, I can do this without any issue:
`response = mkm.account_management.get_all_threads()`
I'm going to copy the whole script, just in case I'm missing some import or something:
```
#!/usr/bin/python3.4
from mkmsdk.mkm import Mkm
from mkmsdk.api_map import _API_MAP
import datetime

# Using API v2.0
mkm = Mkm(_API_MAP["2.0"]["api"], _API_MAP["2.0"]["api_root"])

response = mkm.account_management.find_messages(params={"startDate": "2017-01-01"})
print(response.status_code)
print(response.reason)
print(response.json())
```
And this is what I'm getting:
```
Traceback (most recent call last):
  File "messages-find.py", line 9, in <module>
    response = mkm.account_management.find_messages(params={"startDate": "2017-01-01"})
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/mkm.py", line 43, in __call__
    return self.resolver.resolve(api_map=self.api_map, **kwargs)
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/resolvers.py", line 61, in resolve
    return self.api.request(url=self.url, method=self.method, data=data, params=params, auth_params=auth)
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/api.py", line 42, in request
    return self.handle_response(response)
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/api.py", line 98, in handle_response
    raise exceptions.ConnectionError(response)
mkmsdk.exceptions.ConnectionError: Request failed
Status code: 400
Response message: Bad Request
b'{"mkm_error_description":"User with ID \\u00270\\u0027 doesn\\u0027t exist.","internal_error_code":null,"post_data_field":null,"http_status_code":400,"http_status_code_description":"Bad Request","rfc2616_description_link":"http:\\/\\/www.w3.org\\/Protocols\\/rfc2616\\/rfc2616-sec10.html"}'
```
So, basically a Bad Request (400) with some Exception that I can't understand (sorry I'm not a very fluent Python speaker...;-))

**Comment by nique21** [comment]
And, by the way, if I try this:
`response = mkm.account_management.find_messages(params={"unread": "true"})`
I get this:
```
  File "messages.py", line 16, in <module>
    response = mkm.account_management.find_messages(params={"unread": "true"})
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/mkm.py", line 43, in __call__
    return self.resolver.resolve(api_map=self.api_map, **kwargs)
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/resolvers.py", line 61, in resolve
    return self.api.request(url=self.url, method=self.method, data=data, params=params, auth_params=auth)
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/api.py", line 42, in request
    return self.handle_response(response)
  File "/tmp/magictests/py34proj/lib/python3.4/site-packages/mkmsdk/api.py", line 98, in handle_response
    raise exceptions.ConnectionError(response)
mkmsdk.exceptions.ConnectionError: Request failed
Status code: 400
Response message: Bad Request
b'{"mkm_error_description":"User with ID \\u00270\\u0027 doesn\\u0027t exist.","internal_error_code":null,"post_data_field":null,"http_status_code":400,"http_status_code_description":"Bad Request","rfc2616_description_link":"http:\\/\\/www.w3.org\\/Protocols\\/rfc2616\\/rfc2616-sec10.html"}'
```

**Comment by silvanocerza** [comment]
Seems like in your messages list there is a user with an empty ID, wouldn't surprise me if it's an issue with their backend. 

They either made some undocumented changes to their API and we're creating a bad request or they have some backend issue and this should technically be a 5xx and not a 4xx; given the returned error I believe it's on their end.

Either way I verified the SDK is working as expected, all parameters are used to make the requests and sent to their backend.

I don't know why there might be a user with an empty ID so I suggest you contact them so solve the issue.

**Comment by nique21** [comment]
I'm using a test user that only has 5 message threads. I've checked and all of them have a valid idUser. In fact, if there was an issue with an invalid idUser, I wouldn't get anything or an error, while using mkm.account_management.get_all_threads().

I don't have any other user to test with, but I trust you when you say it's working for you. I want to submit an issue to MKM, but they ask me for all of this:
```
To effectively help with any problems regarding API requests, we need the following information - as complete as possible and independent from any used programming language, libraries, frameworks, etc.:

- request method
- request URI
- complete request headers
- request body, if applicable
- HTTP status code
- complete response headers
- response body, if applicable
```
Can you help me provide them with all this information?

**Comment by silvanocerza** [comment]
If you catch the `ConnectionError` you can recover the failing response and all the necessary information. `ConnectionError.response` is an instance of [requests.Response](https://2.python-requests.org/en/master/api/#requests.Response).

```from mkmsdk import exceptions
try:
    response = mkm.account_management.find_messages(params={"unread": "false"})
except exceptions.ConnectionError as e:
    print(e.response)

**Comment by MarcoPescado** [comment]
Thanks for this SDK!
Sadly my skills are to low, that I can get it up running.
Maybe you can provide me some help?

If I try this short example:
```
`#!/usr/bin/python3.4

from mkmsdk.mkm import Mkm
from mkmsdk.api_map import _API_MAP

# Using API v2.0
mkm = Mkm(_API_MAP["2.0"]["api"], _API_MAP["2.0"]["api_root"])

response = mkm.account_management.account()
print(response.json())`
```
I receive:
```
  File "_MKM.py", line 6, in <module>
    mkm = Mkm(_API_MAP["2.0"]["api"], _API_MAP["2.0"]["api_root"])
KeyError: '2.0'
```
What do I do wrong?
Thx

**Comment by silvanocerza** [comment]
Hi @MarcoPescado, I suggest you open an new issue with more information, so I can better help you and we keep this discussion on topic. :)

**Comment by nique21** [comment]
I have contacted MKM and they have confirmed it is a bug on their side. Their answer:

> Unfortunately this is indeed an error and it exists for a while now. Fixing this is on our list, but I don't have an ETA for this yet.

So, nothing you (or me) can do about it, for now. I'm going to close the issue since it's not a bug on your SDK.

**Comment by silvanocerza** [comment]
Thanks for the update. :)
