### ISSUE TITLE
Product List use example

### ISSUE THREAD

**Issue by flirola** [evonove/mkm-sdk#48]
Hello!

First of all, thank you very much for providing this tool which is great. Being quite new to this, my question might be a bit silly...

I seem not to be able to get the mkm.market_place.product_list() function to work properly. Could you provide an example?

Thanks for the support!

**Comment by silvanocerza** [comment]
Calling `mkm.market_place.product_list()` should be enough. Why do you think it's not working properly? Are there any errors returned? How is the `mkm` object created? 

Are you using API 1.1 or 2.0? `product_list` is available only in v 2.0.

**Comment by flirola** [comment]
I use API 2.0. Here the code I use. Again, I'm new to this, so the function probably works well and I'm calling it in the wrong way.

Below the code I'm using:

"from mkmsdk.mkm import Mkm
from mkmsdk.api_map import _API_MAP

mkm = Mkm(_API_MAP["2.0"]["api"], _API_MAP["2.0"]["api_root"])

response = mkm.market_place.product_list()"

I get the following error:
"mkmsdk.exceptions.ConnectionError: Request failed
Status code: 404
Response message: Not Found"

**Comment by silvanocerza** [comment]
Fixed by #49. 
The endpoint was wrong, it was `/productslist` instead of `/productlist`, it should not fail with 404 anymore. 

I've already drafted and published a new release.

**Comment by flirola** [comment]
Thanks for looking into it!
The tool is definitely what I needed.

Le jeu. 8 août 2019 à 11:27, Silvano Cerza <notifications@github.com> a
écrit :

**Comment by silvanocerza** [comment]
Issue solved. :)
