### ISSUE TITLE
Product List Response Code 400 Bad Request

### ISSUE THREAD

**Issue by Maurnai** [evonove/mkm-sdk#57]
Hello.

I have an issue with the market_place.product_list() function.

The error message looks like that:
raise exceptions.ConnectionError(response)
mkmsdk.exceptions.ConnectionError: Request failed
Status code: 400
Response message: Bad `Request`
b'{"mkm_error_description":"Service currently not available","internal_error_code":null,"post_data_field":null,"http_status_code":400,"http_status_code_description":"Bad Request","rfc2616_description_link":"http:\\/\\/www.w3.org\\/Protocols\\/rfc2616\\/rfc2616-sec10.html"}'

I hope that you can help `me.`
Thanks in advance.

**Comment by silvanocerza** [comment]
Hey @Maurnai, I just gave it a test on the Magic Card Market sandbox site and it seemed to fail in the same way.

I don't see any change in their [API News section](https://api.cardmarket.com/ws/documentation/API_Main_Page) nor in [the endpoint documentation](https://api.cardmarket.com/ws/documentation/API_2.0:Productlist) so this is probably just their backend being flaky, it already happened that they changed some endpoints behaviour without notice and I can't do anything until they update it with new information.

Also the message `"mkm_error_description":"Service currently not available"` makes me think they just disabled it temporarily for some reason without saying a thing.

**Comment by Maurnai** [comment]
Thanks for your quick response.

Maybe they only disabled it on the sandbox server. I haven't tried it on the real server.

**Comment by flirola** [comment]
Dear all,

I don't face any issue on the real server.

Good day to all.
