### ISSUE TITLE
All integration tests fail with 403 Forbidden

### ISSUE THREAD

**Issue by liberforce** [evonove/mkm-sdk#58]
I've been trying for two days to just issue a simple command using the API using several examples found on the internet.
I found your sdk, but still get the same result as my previous attempts: 403 everywhere.

I have tried first with the [sample authentication tokens given in the documentation](https://api.cardmarket.com/ws/documentation/API:Auth_Overview#Working_Examples) 

```
export MKM_APP_TOKEN="bfaD9xOU0SXBhtBP"
export MKM_APP_SECRET="pChvrpp6AEOEwxBIIUBOvWcRG3X9xL4Y"
export MKM_ACCESS_TOKEN="lBY1xptUJ7ZJSK01x4fNwzw8kAe5b10Q"
export MKM_ACCESS_TOKEN_SECRET="hc1wJAOX02pGGJK2uAv1ZOiwS7I9Tpoe"
```

I then tried with the tokens given by cardmarket in the "App Settings" page, still no luck. All 403. Am I doing something wrong, or is the API acces somehow broken?

**Comment by silvanocerza** [comment]
Integration tests are run in the sandbox, the tokens shown in the API docs are just for example's sake you must not use them.

If you want to run integration tests you must create an app in the sandbox server, [this is the exact page](https://sandbox.cardmarket.com/en/Magic/MainPage/showMyAccount) to create it.

I just tested using my sandbox tokens and it works correctly.

**Comment by liberforce** [comment]
Thanks. I did finally achieve to have it work on the production server some time after, but did not know I had to create an account on the sandbox server. Thanks for the information :+1:
