### ISSUE TITLE
add_articles Response Code 401

### ISSUE THREAD

**Issue by Maurnai** [evonove/mkm-sdk#59]
Hello,
unfortunately I ran into another problem with the mkm-sdk.

When I try to add an article to my stock with `response_poststock = mkm_sandbox.stock_management.add_articles(params = {"article":{"idProduct": "1", "idLanguage": "1", "comments": "Inserted through the API", "count": "1", "price": "4", "condition": "EX", "isFoil": "true", "isSigned": "false", "isAltered": "false", "isPlayset": "false"}})` I get a status code 401 returned.

It´s probably me using this function the wrong way with the parameters tho I could not figure out what to change. I also tried other functions and they work just fine.

I hope that you can help me.
Thanks in advance.

**Comment by silvanocerza** [comment]
You should be `data=<your_data>`, `params` is meant for endpoints that expect URL parameters.

Calling `mkm.account_management.vacation(params={"onVacation": "false"})` would make a request to `https://api.cardmarket.com/ws/v2.0/account/vacation?onVacation=false`.

See the usage docs for more examples: https://mkm-sdk.readthedocs.io/en/latest/usage/

**Comment by Maurnai** [comment]
Thank you very much @silvanocerza
