### ISSUE TITLE
Handling Time out errors

### ISSUE THREAD

**Issue by flirola** [evonove/mkm-sdk#60]
Hi everyone,

I'm pretty sure this isn't the right place for the question so I apologize in advance.

I've been facing several time out errors recently with the mkm API. Do you also?

Can you provide advice on how to handle them? I assume a try except would do, but being not so experience in python I'm unsure of the right way to do so.
I'm calling the api with the following code:
response = mkm.market_place.articles(product=idProduct)
and it seems the time out isn't a response type.

Your help would be appreciated.

**Comment by ClemensBuechner** [comment]
I'm have also been facing problems recently, couldn't pinpoint the source of it yet, though. It seems like the time between sending a request and receiving a response from the MKM servers has increased.

**Comment by silvanocerza** [comment]
This is probably not an issue with the SDK, as I said in other issues their backend is always kinda wonky so this doesn't surprise me one bit.

I could suggest to use some sort of exponential backoff to try and send the failing request later on.

**Comment by flirola** [comment]
I agree this has likely nothing to do with the SDK. But as I'm not so
experienced with Python I was wondering if anyone had any advice on how to
handle. For instance, as long as a timeout is return the code retries.

Le jeu. 28 janv. 2021 à 09:45, Silvano Cerza <notifications@github.com> a
écrit :

**Comment by flirola** [comment]
Further looking at the code, it seems the code returns an error if status
code is not between 200 and 399. This forces to have an error handler to
handle 503 (slow down) and 504 timeout.

**Comment by silvanocerza** [comment]
Yes, I think it's technically correct to return an error in those cases. You don't get the response you'd expect from the backend so you have to handle the failure somehow.

You can easily get the returned response from the backend since the expection wraps it. `ConnectionError.response` is an instance of [`requests.Response`](https://requests.readthedocs.io/en/latest/api/#requests.Response).

Something similar to this should ideally work.
```
from mkmsdk.exceptions import ConnectionError

try:
    // You make the request here
except ConnectionError as e:
    if e.response.status_code == 503:
        // handle this
    elif e.response.status_code == 504:
        // handle that
    else:
        // or else
```

**Comment by flirola** [comment]
All clear! Thanks for the reply!

Le dim. 31 janv. 2021 à 12:56, Silvano Cerza <notifications@github.com> a
écrit :
