### ISSUE TITLE
403 Forbidden with all request in sandbox

### ISSUE THREAD

**Issue by enrico9034** [evonove/mkm-sdk#71]
Hi I try this sdk for an university project and I created a widget in sandbox cardmarket's server, but when I try run an API I receive only 403 and 401 errors.
![gnome-shell-screenshot-UKX060](https://user-images.githubusercontent.com/24253800/127128971-e64d7e78-3382-4eeb-b43f-3180b2e988cc.png)

**Comment by enrico9034** [comment]
update: now I try ```response = mkm_sandbox.market_place.user(user='enrico9034')``` and work, but i need ```market_place.price_guide```.
someone can help me?

**Comment by SukiCZ** [comment]
Hi,
I believe this is not and issue of `mkmsdk` rather than Card Market itself.
The documentation for this endpoint says

> Attention: This request is restricted to Widget apps, 3rd party apps, and Dedicated apps of powersellers and professionals

Refer to MKM documentation for more details.
https://api.cardmarket.com/ws/documentation/API_2.0:PriceGuide
