### ISSUE TITLE
POST data for /stock

### ISSUE THREAD

**Issue by nicolaennio** [evonove/mkm-sdk#9]
Hi,

I am toying with the code and I am not able to use the /stock call for adding an article to the stock. I suspect it's due to the fact that the call in https://github.com/evonove/mkm-sdk/blob/master/mkmsdk/resolvers.py#L57 does not support a 'data' key in the args for a POST call, but I may have not properly understood the code.

Anyway thanks, it's very useful!

**Comment by Alien1993** [comment]
What kind of error you get back? What data are you trying to POST?

**Comment by nicolaennio** [comment]
I tried to add an item to my stock in the following way:

mkm.stock_management.post_stock(data=data)

with data a dictionary with the idProduct or directly an XML string. Either ways I got

{'error': '{"error":"Invalid POST data"}'}

**Comment by Alien1993** [comment]
Thanks for the info. I'll try to fix ASAP.

**Comment by Alien1993** [comment]
Fixed in PR #11.
